name: zora_nft_marketplace
description: A Flutter app to fetch NFT market info from Zora
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.6.1
  http: ^0.13.5
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

